#!/bin/bash

export EDITOR='nvim'

export LESS=-R

export AWS_VAULT_BACKEND=pass

# Fix gpg not asking for password
export GPG_TTY=$(tty)

# Managed homebrew install on OS X
[[ -d /opt/homebrew/bin ]] && export PATH="/opt/homebrew/bin:$PATH"

# Homebrew on linux
[[ -d /home/linuxbrew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# .local/bin
[[ -d $HOME/.local/bin ]] && export PATH="$HOME/.local/bin:$PATH"

# Load rbenv
command -v rbenv &> /dev/null && eval "$(rbenv init -)"
