#!/bin/bash

# Set EDITOR
export EDITOR='nvim'

export LESS=-R

export AWS_VAULT_BACKEND=pass

# Fix gpg not asking for password
export GPG_TTY=$(tty)

# Set paths for golang
# This is where it ends up on OS X
if [ -d "/usr/local/opt/go/libexec" ]; then
  export GOROOT=/usr/local/opt/go/libexec
# Should be here if installed manually
else
  export GOROOT=/usr/local/go
fi
# Use .go instead of go
export GOPATH=$HOME/.go

# Path to powerline status libs
if command -v pip3 &> /dev/null; then
  # Have to do this nonsense to get python package dir, really stupid language
  local python_package_path="$(pip3 show powerline-status | grep "Location" | awk '{ FS = ":"; print $2 }')"

  # No idea why this installs to different locations on different machines
  if [ -d "$python_package_path/powerline" ]; then
    export POWERLINE_LIB_PATH=$python_package_path/powerline
  elif [ -d "$python_package_path/powerline-status" ]; then
    export POWERLINE_LIB_PATH=$python_package_path/powerline-status
  fi
fi

# Add library paths to path
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$GOROOT/bin:$GOPATH/bin:$HOME/.local/bin:$HOME/.rbenv/bin:$PATH"

# N install
export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).

# homebrew on linux
[[ -d /home/linuxbrew ]] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Load rbenv
eval "$(rbenv init -)"
